### ISSUE TITLE
MongoHQ issues

### ISSUE THREAD

**Issue by choppen5** [choppen5/client-acd#10]
User @judamarto reported:

"Hello, I deployed using Option 1 to Heroku and it seems the app keep crashing due to this error. Appreciate if you can let me know on how to fix it.

/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/uri/generic.rb:214:in `initialize': the scheme mongodb does not accept registry part: heroku:OV-g5g2GmsXQy8rQTszY8U1f1s7I3AmCsmRHmKHyNAgNjbr1f-0D6nfmZW5qarw4eI_UJX3OBkr2xItajW4ltA@candidate.37.mongolayer.com:10653,candidate.18.mongolayer.com:10683 (or bad hostname?) (URI::InvalidURIError)"

He also found a solution using MongoLab.  Trying that now.

**Comment by choppen5** [comment]
Fixed, now deploys with MongoLab instead of MongoHQ which is free.

**Comment by tkyocum** [comment]
FYI - I suspect the issue you're seeing is the fact that @judamarto is trying to use a replica set URI whereas the MongoLab example is not (apparently) a replica set.
