### ISSUE TITLE
Heroku failed to build.

### ISSUE THREAD

**Issue by weissben** [choppen5/client-acd#11]
Chose Option 1, but Heroku will not build. I suspect its the gems version, but unclear.

-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from http://rubygems.org/............
       Fetching version metadata from http://rubygems.org/...
       Fetching dependency metadata from http://rubygems.org/..
       Installing addressable 2.3.5
       Installing builder 3.2.0
       Installing bson 1.9.2
       Installing daemons 1.1.4
       Installing eventmachine 1.0.3 with native extensions
       Installing json 1.8.0 with native extensions
       Installing multi_json 1.6.1
       Installing rack 1.5.2
       Installing tilt 1.3.4
       Using bundler 1.11.2
       Installing bson_ext 1.9.2 with native extensions
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160504-214-2lup9v.rb extconf.rb
       checking for rb_trap_immediate in ruby.h,rubysig.h... no
       checking for rb_thread_blocking_region()... no
       checking for inotify_init() in sys/inotify.h... yes
       checking for writev() in sys/uio.h... yes
       checking for rb_wait_for_single_fd()... yes
       checking for rb_enable_interrupt()... no
       checking for rb_time_new()... yes
       checking for sys/event.h... no
       checking for epoll_create() in sys/epoll.h... yes
       creating Makefile
       make "DESTDIR=" clean
       make "DESTDIR="
       compiling cmain.cpp
       compiling page.cpp
       compiling pipe.cpp
       compiling em.cpp
       em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
       em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       em.cpp: In member function ‘int SelectData_t::_Select()’:
       em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
       return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
       ^
       em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
       em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       make: *** [em.o] Error 1
       make failed, exit code 2
       Gem files will remain installed in /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
       Results logged to /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160504-214-1hpj4hi.rb extconf.rb
       creating Makefile
       make "DESTDIR=" clean
       make "DESTDIR="
       compiling generator.c
       In file included from generator.c:1:0:
       ../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
       ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       ../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       make: *** [generator.o] Error 1
       make failed, exit code 2
       Gem files will remain installed in /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/gems/json-1.8.0 for inspection.
       Results logged to /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/json-1.8.0/gem_make.out
       Installing mongo 1.9.2
       Installing jwt 0.1.6
       Installing rack-protection 1.4.0
       An error occurred while installing eventmachine (1.0.3), and Bundler cannot
       continue.
       Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
       Bundler Output: Fetching gem metadata from http://rubygems.org/............
       Fetching version metadata from http://rubygems.org/...
       Fetching dependency metadata from http://rubygems.org/..
       Installing addressable 2.3.5
       Installing builder 3.2.0
       Installing bson 1.9.2
       Installing daemons 1.1.4
       Installing eventmachine 1.0.3 with native extensions
       Installing json 1.8.0 with native extensions
       Installing multi_json 1.6.1
       Installing rack 1.5.2
       Installing tilt 1.3.4
       Using bundler 1.11.2
       Installing bson_ext 1.9.2 with native extensions
       
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160504-214-2lup9v.rb extconf.rb
       checking for rb_trap_immediate in ruby.h,rubysig.h... no
       checking for rb_thread_blocking_region()... no
       checking for inotify_init() in sys/inotify.h... yes
       checking for writev() in sys/uio.h... yes
       checking for rb_wait_for_single_fd()... yes
       checking for rb_enable_interrupt()... no
       checking for rb_time_new()... yes
       checking for sys/event.h... no
       checking for epoll_create() in sys/epoll.h... yes
       creating Makefile
       
       make "DESTDIR=" clean
       
       make "DESTDIR="
       compiling cmain.cpp
       compiling page.cpp
       compiling pipe.cpp
       compiling em.cpp
       em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
       em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       em.cpp: In member function ‘int SelectData_t::_Select()’:
       em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
       return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
       ^
       em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
       em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       make: *** [em.o] Error 1
       
       make failed, exit code 2
       
       Gem files will remain installed in /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
       Results logged to /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
       
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160504-214-1hpj4hi.rb extconf.rb
       creating Makefile
       
       make "DESTDIR=" clean
       
       make "DESTDIR="
       compiling generator.c
       In file included from generator.c:1:0:
       ../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
       ../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       ../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
       VALUE result = rb_str_new(FBUFFER_PAIR(fb));
       ^
       make: *** [generator.o] Error 1
       
       make failed, exit code 2
       
       Gem files will remain installed in /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/gems/json-1.8.0 for inspection.
       Results logged to /tmp/build_2d54a5039f38db0e84134d6aa7dbbce2/choppen5-client-acd-374d73f/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/json-1.8.0/gem_make.out
       Installing mongo 1.9.2
       Installing jwt 0.1.6
       Installing rack-protection 1.4.0
       An error occurred while installing eventmachine (1.0.3), and Bundler cannot
       continue.
       Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by bcoyle73** [comment]
@weissben I believe it's a ruby version thing.  I had someone point out a similar issue on my forked version of @choppen5 demo.  I fixed it with the commit's in Feb....https://github.com/bcoyle73/client-acd/commits/master

**Comment by choppen5** [comment]
Thanks for the report.  @bcoyle73 fix will work, I also updated it to use eventmachine 1.0.4 and it shoudl work now.
