### ISSUE TITLE
Can this client-acd be ported for Force.com Sites - VFP?

### ISSUE THREAD

**Issue by judamarto** [choppen5/client-acd#8]
Hi @choppen5, just wondering if this client-acd can be ported to Force.com Sites/visualforce pages? I understand Force.com doesn't support websockets yet, however it supports CometD for Streaming API. Let me know your thought. Any other gotchas?

**Comment by choppen5** [comment]
Yes.. but you would be better rebuilding it than "porting" it.  You can achieve the same things with the Streaming API, using SFDC as the agent state backend.   For a basic call, you can see this: https://github.com/choppen5/TwilioSalesforceClick2Dial
